version: '3.8'

services:
  # Service principal RAG CGI API (ultra-léger)
  rag-cgi-api:
    build:
      context: .
      dockerfile: Dockerfile.light
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./data:/app/data
      - ./vector_db:/app/vector_db
      - ./.env:/app/.env
    environment:
      - ENVIRONMENT=development
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - REDIS_URL=redis://redis:6379
      - VECTOR_STORE_TYPE=faiss
      - PERSIST_DIRECTORY=./vector_db
    depends_on:
      - redis
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Cache Redis léger
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # Interface de test simple
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.light.conf:/etc/nginx/nginx.conf
    depends_on:
      - rag-cgi-api
    restart: unless-stopped

volumes:
  redis_data:

networks:
  default:
    name: rag-cgi-light-network 